<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Provides testing capabilities during testing of Azure Data Factory integrations</Description>
    <PackageTags>Azure;Testing;DataFactory</PackageTags>
    <PackageId>Arcus.Testing.Integration.DataFactory</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="[1.*,2.0.0)" />
    <PackageReference Include="Azure.ResourceManager.DataFactory" Version="[1.*,2.0.0)" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="[10.*,11.0.0)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Arcus.Testing.Assert\Arcus.Testing.Assert.csproj" />
  </ItemGroup>

</Project>
