# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/configuration/ and in linters documentation

DISABLE_LINTERS:
  - COPYPASTE_JSCPD
  - SPELL_CSPELL
  - REPOSITORY_TRIVY
  - REPOSITORY_GRYPE

REPOSITORY_DEVSKIM_CONFIG_FILE: '/.github/.devskim.json'
REPOSITORY_DEVSKIM_ARGUMENTS: '-f text'

REPOSITORY_CHECKOV_CONFIG_FILE: '/.github/.checkov.yml'

CSHARP_DOTNET_FORMAT_ARGUMENTS: './src/Arcus.Testing.sln'
